### ISSUE TITLE
Latex fontspec error

### ISSUE THREAD

**Issue by lighterhouse** [cfrpg/FlightControl#1]
When i use the "Xelatex" to complie the flightcontrol.tex, it has many fontspec error, how to solve this problem?
![1](https://user-images.githubusercontent.com/49912866/61714650-f5f55200-ad8d-11e9-84df-a402cea6e62e.PNG)

**Comment by cfrpg** [comment]
文档使用的模板中的字体为Adobe字体(宋体，黑体，楷体，仿宋)，需要另行购买或下载并安装。此文档在编写的时候使用的是TeXLive 2017环境，不保证其他环境中可以正常编译。
