### ISSUE TITLE
零点

### ISSUE THREAD

**Issue by lighterhouse** [cfrpg/FlightControl#2]
请问作者大大求根轨迹增益时零点是如何求得的

**Comment by cfrpg** [comment]
作者并不懂自动控制原理，似乎没有求零点。单一变量反馈增益是直接在根轨迹图上找点查看对应增益取得的orz。

**Comment by lighterhouse** [comment]
求单一变量根轨迹时需要传递函数，那这个传递函数是怎么得到的呢（主要是看到pdf里图1-1里有两个零点不知道是如何来的）

**Comment by lighterhouse** [comment]
> 作者并不懂自动控制原理，似乎没有求零点。单一变量反馈增益是直接在根轨迹图上找点查看对应增益取得的orz。
